### ISSUE TITLE
Question about import/export

### ISSUE THREAD

**Issue by santervo** [lokalise/ruby-lokalise-api#32]
I have few issues with importing and exporting using the api client.

1.

On imports all empty values are modified to empty string

For example

```
fi:
  somekey:
```

gets modified to:

```
fi:
  somekey: ''
```

after exporting it to lokalise and importing it back. That's an issue because rails translation does not anymore detect it anymore as missing value and replace it with default language value.

2.

On export empty object gets modified like this:

```
en:
  i18n:
    transliterate:
      rule: {}
```

is modified to:

```
en:
 i18n:
    transliterate:
      rule: '{"one":"","other":""}'
```

This causes "I18n::ArgumentError: Transliteration rule must be a proc or a hash." when trying to use I18n.transliterate function

What is reason behind these modifications, and are there some configuration options or something?
